version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workscrapping_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/workscrapping_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: workscrapping_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workscrapping_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
