services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workscrapping_app
    restart: always
    ports:
      - 30506:3000
    environment:
      - NODE_ENV=production
