version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workscrapping_app
    restart: always
    ports:
      - "${APP_PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=production
